### PR TITLE
Upgrade react-scripts fix security vunerability.

### PR DESCRIPTION
**Pull request by bryanmikaelian**
## What's in this PR

This PR upgrades `react-scripts` to resolve a security vunerability with `lodash.template` and `lodash`

Output showing we are on the right version

```
➜ yarn why lodash.template
yarn why v1.13.0
[1/4] 🤔  Why do we have the module "lodash.template"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "lodash.template@4.5.0"
info Reasons this module exists
   - "react-scripts#workbox-webpack-plugin#workbox-build" depends on it
   - Hoisted from "react-scripts#workbox-webpack-plugin#workbox-build#lodash.template"
   - Hoisted from "react-scripts#postcss-preset-env#postcss-initial#lodash.template"
info Disk size without dependencies: "60KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 2
✨  Done in 0.80s.
```

```
➜ yarn why lodash
yarn why v1.13.0
[1/4] 🤔  Why do we have the module "lodash"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "lodash@4.17.14"
info Reasons this module exists
   - "@babel#core" depends on it
   - Hoisted from "@babel#core#lodash"
   - Hoisted from "react-scripts#webpack-manifest-plugin#lodash"
   - Hoisted from "react-scripts#eslint-plugin-flowtype#lodash"
   - Hoisted from "react-scripts#@babel#core#lodash"
   - Hoisted from "react-scripts#eslint#lodash"
   - Hoisted from "@babel#core#@babel#generator#lodash"
   - Hoisted from "@babel#plugin-transform-classes#@babel#helper-define-map#lodash"
   - Hoisted from "react-scripts#eslint-plugin-import#lodash"
   - Hoisted from "@babel#core#@babel#types#lodash"
   - Hoisted from "@babel#core#@babel#traverse#lodash"
   - Hoisted from "react-scripts#html-webpack-plugin#lodash"
   - Hoisted from "react-scripts#babel-preset-react-app#@babel#core#lodash"
   - Hoisted from "react-scripts#react-dev-utils#inquirer#lodash"
   - Hoisted from "react-scripts#webpack-dev-server#http-proxy-middleware#lodash"
   - Hoisted from "react-scripts#eslint#inquirer#lodash"
   - Hoisted from "react-scripts#eslint#table#lodash"
   - Hoisted from "react-scripts#optimize-css-assets-webpack-plugin#last-call-webpack-plugin#lodash"
   - Hoisted from "react-scripts#babel-preset-react-app#@babel#preset-env#@babel#plugin-transform-block-scoping#lodash"
   - Hoisted from "react-scripts#babel-preset-react-app#@babel#preset-env#@babel#plugin-transform-modules-umd#@babel#helper-module-transforms#lodash"
   - Hoisted from "react-scripts#babel-preset-react-app#@babel#preset-env#@babel#plugin-transform-sticky-regex#@babel#helper-regex#lodash"
   - Hoisted from "react-scripts#jest-environment-jsdom-fourteen#jsdom#request-promise-native#request-promise-core#lodash"
info Disk size without dependencies: "4.86MB"
info Disk size with unique dependencies: "4.86MB"
info Disk size with transitive dependencies: "4.86MB"
info Number of shared dependencies: 0
✨  Done in 0.83s.
```

### CODE REVIEW

**Comment by collinvandyck** [comment]
I believe lodash-template was also part of the vulnerability report.  Does that need to be updated specifically as well?

**Comment by bryanmikaelian** [comment]
@collinvandyck Oh! Good catch. Fixed. We'll probably need to regenerate the site as well.

**Comment by collinvandyck** [comment]
Cool. want to generate the site and add a commit to this PR?

**Comment by bryanmikaelian** [comment]
Went ahead with the better fix of bumping `react-scripts`. This did require a regen of the site.

**Comment by collinvandyck** [comment]
It looks like we wrote another website fragment and didn't delete the old one.  Does our gensite target need to rm -r `website/gen/*` first?

**Comment by bryanmikaelian** [comment]
@collinvandyck oof, looks like that's been the case for a while. https://github.com/segmentio/ctlstore/tree/master/website/gen

+1 to fixing that script in a separate PR. In the meantime, I can do a one off fix here

**Comment by collinvandyck** [comment]
🚢

**Pull request merged**
